// source: cosmos/orm/v1alpha1/schema.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');

goog.exportSymbol('proto.cosmos.orm.v1alpha1.SchemaDescriptor', null, global);
goog.exportSymbol('proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry', null, global);
goog.exportSymbol('proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cosmos.orm.v1alpha1.SchemaDescriptor.repeatedFields_, null);
};
goog.inherits(proto.cosmos.orm.v1alpha1.SchemaDescriptor, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cosmos.orm.v1alpha1.SchemaDescriptor.displayName = 'proto.cosmos.orm.v1alpha1.SchemaDescriptor';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.repeatedFields_, null);
};
goog.inherits(proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.displayName = 'proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.displayName = 'proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.prototype.toObject = function(opt_includeInstance) {
  return proto.cosmos.orm.v1alpha1.SchemaDescriptor.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cosmos.orm.v1alpha1.SchemaDescriptor} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.toObject = function(includeInstance, msg) {
  var f, obj = {
    files: (f = msg.getFiles()) && google_protobuf_descriptor_pb.FileDescriptorSet.toObject(includeInstance, f),
    modulesList: jspb.Message.toObjectList(msg.getModulesList(),
    proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cosmos.orm.v1alpha1.SchemaDescriptor;
  return proto.cosmos.orm.v1alpha1.SchemaDescriptor.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cosmos.orm.v1alpha1.SchemaDescriptor} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_descriptor_pb.FileDescriptorSet;
      reader.readMessage(value,google_protobuf_descriptor_pb.FileDescriptorSet.deserializeBinaryFromReader);
      msg.setFiles(value);
      break;
    case 2:
      var value = new proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry;
      reader.readMessage(value,proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.deserializeBinaryFromReader);
      msg.addModules(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cosmos.orm.v1alpha1.SchemaDescriptor.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cosmos.orm.v1alpha1.SchemaDescriptor} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFiles();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_descriptor_pb.FileDescriptorSet.serializeBinaryToWriter
    );
  }
  f = message.getModulesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    prefix: msg.getPrefix_asB64(),
    filesList: jspb.Message.toObjectList(msg.getFilesList(),
    proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry;
  return proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPrefix(value);
      break;
    case 3:
      var value = new proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry;
      reader.readMessage(value,proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.deserializeBinaryFromReader);
      msg.addFiles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPrefix_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getFilesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry} returns this
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bytes prefix = 2;
 * @return {!(string|Uint8Array)}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.getPrefix = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes prefix = 2;
 * This is a type-conversion wrapper around `getPrefix()`
 * @return {string}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.getPrefix_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPrefix()));
};


/**
 * optional bytes prefix = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPrefix()`
 * @return {!Uint8Array}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.getPrefix_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPrefix()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry} returns this
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.setPrefix = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * repeated FileEntry files = 3;
 * @return {!Array<!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry>}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.getFilesList = function() {
  return /** @type{!Array<!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry, 3));
};


/**
 * @param {!Array<!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry>} value
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry} returns this
*/
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.setFilesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.addFiles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry} returns this
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry.prototype.clearFilesList = function() {
  return this.setFilesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    fileName: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry;
  return proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFileName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getFileName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional uint32 id = 1;
 * @return {number}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry} returns this
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string file_name = 2;
 * @return {string}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.prototype.getFileName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry} returns this
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.FileEntry.prototype.setFileName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.FileDescriptorSet files = 1;
 * @return {?proto.google.protobuf.FileDescriptorSet}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.prototype.getFiles = function() {
  return /** @type{?proto.google.protobuf.FileDescriptorSet} */ (
    jspb.Message.getWrapperField(this, google_protobuf_descriptor_pb.FileDescriptorSet, 1));
};


/**
 * @param {?proto.google.protobuf.FileDescriptorSet|undefined} value
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor} returns this
*/
proto.cosmos.orm.v1alpha1.SchemaDescriptor.prototype.setFiles = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor} returns this
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.prototype.clearFiles = function() {
  return this.setFiles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.prototype.hasFiles = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated ModuleEntry modules = 2;
 * @return {!Array<!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry>}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.prototype.getModulesList = function() {
  return /** @type{!Array<!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry, 2));
};


/**
 * @param {!Array<!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry>} value
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor} returns this
*/
proto.cosmos.orm.v1alpha1.SchemaDescriptor.prototype.setModulesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry}
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.prototype.addModules = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.cosmos.orm.v1alpha1.SchemaDescriptor.ModuleEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cosmos.orm.v1alpha1.SchemaDescriptor} returns this
 */
proto.cosmos.orm.v1alpha1.SchemaDescriptor.prototype.clearModulesList = function() {
  return this.setModulesList([]);
};


goog.object.extend(exports, proto.cosmos.orm.v1alpha1);
