// source: uptick/erc721/v1/tx.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_api_annotations_pb = require('../../../google/api/annotations_pb.js');

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');

var ibc_core_client_v1_client_pb = require('../../../ibc/core/client/v1/client_pb.js');

goog.exportSymbol('proto.uptick.erc721.v1.MsgConvertERC721', null, global);
goog.exportSymbol('proto.uptick.erc721.v1.MsgConvertERC721Response', null, global);
goog.exportSymbol('proto.uptick.erc721.v1.MsgConvertNFT', null, global);
goog.exportSymbol('proto.uptick.erc721.v1.MsgConvertNFTResponse', null, global);
goog.exportSymbol('proto.uptick.erc721.v1.MsgTransferERC721', null, global);
goog.exportSymbol('proto.uptick.erc721.v1.MsgTransferERC721Response', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.uptick.erc721.v1.MsgConvertNFT = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.uptick.erc721.v1.MsgConvertNFT.repeatedFields_, null);
};
goog.inherits(proto.uptick.erc721.v1.MsgConvertNFT, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.uptick.erc721.v1.MsgConvertNFT.displayName = 'proto.uptick.erc721.v1.MsgConvertNFT';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.uptick.erc721.v1.MsgConvertNFTResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.uptick.erc721.v1.MsgConvertNFTResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.uptick.erc721.v1.MsgConvertNFTResponse.displayName = 'proto.uptick.erc721.v1.MsgConvertNFTResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.uptick.erc721.v1.MsgConvertERC721 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.uptick.erc721.v1.MsgConvertERC721.repeatedFields_, null);
};
goog.inherits(proto.uptick.erc721.v1.MsgConvertERC721, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.uptick.erc721.v1.MsgConvertERC721.displayName = 'proto.uptick.erc721.v1.MsgConvertERC721';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.uptick.erc721.v1.MsgConvertERC721Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.uptick.erc721.v1.MsgConvertERC721Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.uptick.erc721.v1.MsgConvertERC721Response.displayName = 'proto.uptick.erc721.v1.MsgConvertERC721Response';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.uptick.erc721.v1.MsgTransferERC721 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.uptick.erc721.v1.MsgTransferERC721, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.uptick.erc721.v1.MsgTransferERC721.displayName = 'proto.uptick.erc721.v1.MsgTransferERC721';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.uptick.erc721.v1.MsgTransferERC721Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.uptick.erc721.v1.MsgTransferERC721Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.uptick.erc721.v1.MsgTransferERC721Response.displayName = 'proto.uptick.erc721.v1.MsgTransferERC721Response';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.uptick.erc721.v1.MsgConvertNFT.repeatedFields_ = [2,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.toObject = function(opt_includeInstance) {
  return proto.uptick.erc721.v1.MsgConvertNFT.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.uptick.erc721.v1.MsgConvertNFT} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgConvertNFT.toObject = function(includeInstance, msg) {
  var f, obj = {
    classId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    cosmosTokenIdsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    evmReceiver: jspb.Message.getFieldWithDefault(msg, 3, ""),
    cosmosSender: jspb.Message.getFieldWithDefault(msg, 4, ""),
    evmContractAddress: jspb.Message.getFieldWithDefault(msg, 5, ""),
    evmTokenIdsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT}
 */
proto.uptick.erc721.v1.MsgConvertNFT.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.uptick.erc721.v1.MsgConvertNFT;
  return proto.uptick.erc721.v1.MsgConvertNFT.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.uptick.erc721.v1.MsgConvertNFT} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT}
 */
proto.uptick.erc721.v1.MsgConvertNFT.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClassId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addCosmosTokenIds(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvmReceiver(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCosmosSender(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvmContractAddress(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addEvmTokenIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.uptick.erc721.v1.MsgConvertNFT.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.uptick.erc721.v1.MsgConvertNFT} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgConvertNFT.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClassId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCosmosTokenIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getEvmReceiver();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCosmosSender();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getEvmContractAddress();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getEvmTokenIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
};


/**
 * optional string class_id = 1;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.getClassId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT} returns this
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.setClassId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string cosmos_token_ids = 2;
 * @return {!Array<string>}
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.getCosmosTokenIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT} returns this
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.setCosmosTokenIdsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT} returns this
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.addCosmosTokenIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT} returns this
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.clearCosmosTokenIdsList = function() {
  return this.setCosmosTokenIdsList([]);
};


/**
 * optional string evm_receiver = 3;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.getEvmReceiver = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT} returns this
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.setEvmReceiver = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string cosmos_sender = 4;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.getCosmosSender = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT} returns this
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.setCosmosSender = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string evm_contract_address = 5;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.getEvmContractAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT} returns this
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.setEvmContractAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated string evm_token_ids = 6;
 * @return {!Array<string>}
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.getEvmTokenIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT} returns this
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.setEvmTokenIdsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT} returns this
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.addEvmTokenIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.uptick.erc721.v1.MsgConvertNFT} returns this
 */
proto.uptick.erc721.v1.MsgConvertNFT.prototype.clearEvmTokenIdsList = function() {
  return this.setEvmTokenIdsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.uptick.erc721.v1.MsgConvertNFTResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.uptick.erc721.v1.MsgConvertNFTResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.uptick.erc721.v1.MsgConvertNFTResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgConvertNFTResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.uptick.erc721.v1.MsgConvertNFTResponse}
 */
proto.uptick.erc721.v1.MsgConvertNFTResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.uptick.erc721.v1.MsgConvertNFTResponse;
  return proto.uptick.erc721.v1.MsgConvertNFTResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.uptick.erc721.v1.MsgConvertNFTResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.uptick.erc721.v1.MsgConvertNFTResponse}
 */
proto.uptick.erc721.v1.MsgConvertNFTResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.uptick.erc721.v1.MsgConvertNFTResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.uptick.erc721.v1.MsgConvertNFTResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.uptick.erc721.v1.MsgConvertNFTResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgConvertNFTResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.uptick.erc721.v1.MsgConvertERC721.repeatedFields_ = [2,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.toObject = function(opt_includeInstance) {
  return proto.uptick.erc721.v1.MsgConvertERC721.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.uptick.erc721.v1.MsgConvertERC721} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgConvertERC721.toObject = function(includeInstance, msg) {
  var f, obj = {
    evmContractAddress: jspb.Message.getFieldWithDefault(msg, 1, ""),
    evmTokenIdsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    cosmosReceiver: jspb.Message.getFieldWithDefault(msg, 3, ""),
    evmSender: jspb.Message.getFieldWithDefault(msg, 4, ""),
    classId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    cosmosTokenIdsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721}
 */
proto.uptick.erc721.v1.MsgConvertERC721.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.uptick.erc721.v1.MsgConvertERC721;
  return proto.uptick.erc721.v1.MsgConvertERC721.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.uptick.erc721.v1.MsgConvertERC721} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721}
 */
proto.uptick.erc721.v1.MsgConvertERC721.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvmContractAddress(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addEvmTokenIds(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCosmosReceiver(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvmSender(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setClassId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addCosmosTokenIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.uptick.erc721.v1.MsgConvertERC721.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.uptick.erc721.v1.MsgConvertERC721} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgConvertERC721.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEvmContractAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEvmTokenIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getCosmosReceiver();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEvmSender();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getClassId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCosmosTokenIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
};


/**
 * optional string evm_contract_address = 1;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.getEvmContractAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721} returns this
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.setEvmContractAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string evm_token_ids = 2;
 * @return {!Array<string>}
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.getEvmTokenIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721} returns this
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.setEvmTokenIdsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721} returns this
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.addEvmTokenIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721} returns this
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.clearEvmTokenIdsList = function() {
  return this.setEvmTokenIdsList([]);
};


/**
 * optional string cosmos_receiver = 3;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.getCosmosReceiver = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721} returns this
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.setCosmosReceiver = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string evm_sender = 4;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.getEvmSender = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721} returns this
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.setEvmSender = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string class_id = 5;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.getClassId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721} returns this
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.setClassId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated string cosmos_token_ids = 6;
 * @return {!Array<string>}
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.getCosmosTokenIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721} returns this
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.setCosmosTokenIdsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721} returns this
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.addCosmosTokenIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721} returns this
 */
proto.uptick.erc721.v1.MsgConvertERC721.prototype.clearCosmosTokenIdsList = function() {
  return this.setCosmosTokenIdsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.uptick.erc721.v1.MsgConvertERC721Response.prototype.toObject = function(opt_includeInstance) {
  return proto.uptick.erc721.v1.MsgConvertERC721Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.uptick.erc721.v1.MsgConvertERC721Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgConvertERC721Response.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721Response}
 */
proto.uptick.erc721.v1.MsgConvertERC721Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.uptick.erc721.v1.MsgConvertERC721Response;
  return proto.uptick.erc721.v1.MsgConvertERC721Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.uptick.erc721.v1.MsgConvertERC721Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.uptick.erc721.v1.MsgConvertERC721Response}
 */
proto.uptick.erc721.v1.MsgConvertERC721Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.uptick.erc721.v1.MsgConvertERC721Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.uptick.erc721.v1.MsgConvertERC721Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.uptick.erc721.v1.MsgConvertERC721Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgConvertERC721Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.toObject = function(opt_includeInstance) {
  return proto.uptick.erc721.v1.MsgTransferERC721.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.uptick.erc721.v1.MsgTransferERC721} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgTransferERC721.toObject = function(includeInstance, msg) {
  var f, obj = {
    evmContractAddress: jspb.Message.getFieldWithDefault(msg, 1, ""),
    evmTokenIds: jspb.Message.getFieldWithDefault(msg, 2, ""),
    sourcePort: jspb.Message.getFieldWithDefault(msg, 3, ""),
    sourceChannel: jspb.Message.getFieldWithDefault(msg, 4, ""),
    classId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    cosmosTokenIds: jspb.Message.getFieldWithDefault(msg, 6, ""),
    evmSender: jspb.Message.getFieldWithDefault(msg, 7, ""),
    cosmosReceiver: jspb.Message.getFieldWithDefault(msg, 8, ""),
    timeoutHeight: jspb.Message.getFieldWithDefault(msg, 9, 0),
    timeoutTimestamp: jspb.Message.getFieldWithDefault(msg, 10, 0),
    memo: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721}
 */
proto.uptick.erc721.v1.MsgTransferERC721.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.uptick.erc721.v1.MsgTransferERC721;
  return proto.uptick.erc721.v1.MsgTransferERC721.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.uptick.erc721.v1.MsgTransferERC721} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721}
 */
proto.uptick.erc721.v1.MsgTransferERC721.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvmContractAddress(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvmTokenIds(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSourcePort(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSourceChannel(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setClassId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCosmosTokenIds(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvmSender(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setCosmosReceiver(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimeoutHeight(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimeoutTimestamp(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.uptick.erc721.v1.MsgTransferERC721.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.uptick.erc721.v1.MsgTransferERC721} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgTransferERC721.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEvmContractAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEvmTokenIds();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSourcePort();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSourceChannel();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getClassId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCosmosTokenIds();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getEvmSender();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getCosmosReceiver();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getTimeoutHeight();
  if (f !== 0) {
    writer.writeUint64(
      9,
      f
    );
  }
  f = message.getTimeoutTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
  f = message.getMemo();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional string evm_contract_address = 1;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.getEvmContractAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721} returns this
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.setEvmContractAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string evm_token_ids = 2;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.getEvmTokenIds = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721} returns this
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.setEvmTokenIds = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string source_port = 3;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.getSourcePort = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721} returns this
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.setSourcePort = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string source_channel = 4;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.getSourceChannel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721} returns this
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.setSourceChannel = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string class_id = 5;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.getClassId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721} returns this
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.setClassId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string cosmos_token_ids = 6;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.getCosmosTokenIds = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721} returns this
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.setCosmosTokenIds = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string evm_sender = 7;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.getEvmSender = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721} returns this
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.setEvmSender = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string cosmos_receiver = 8;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.getCosmosReceiver = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721} returns this
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.setCosmosReceiver = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional uint64 timeout_height = 9;
 * @return {number}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.getTimeoutHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721} returns this
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.setTimeoutHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint64 timeout_timestamp = 10;
 * @return {number}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.getTimeoutTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721} returns this
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.setTimeoutTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional string memo = 11;
 * @return {string}
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.getMemo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721} returns this
 */
proto.uptick.erc721.v1.MsgTransferERC721.prototype.setMemo = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.uptick.erc721.v1.MsgTransferERC721Response.prototype.toObject = function(opt_includeInstance) {
  return proto.uptick.erc721.v1.MsgTransferERC721Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.uptick.erc721.v1.MsgTransferERC721Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgTransferERC721Response.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721Response}
 */
proto.uptick.erc721.v1.MsgTransferERC721Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.uptick.erc721.v1.MsgTransferERC721Response;
  return proto.uptick.erc721.v1.MsgTransferERC721Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.uptick.erc721.v1.MsgTransferERC721Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.uptick.erc721.v1.MsgTransferERC721Response}
 */
proto.uptick.erc721.v1.MsgTransferERC721Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.uptick.erc721.v1.MsgTransferERC721Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.uptick.erc721.v1.MsgTransferERC721Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.uptick.erc721.v1.MsgTransferERC721Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.erc721.v1.MsgTransferERC721Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.uptick.erc721.v1);
