/**
 * @fileoverview gRPC-Web generated client stub for uptick.cw721.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: uptick/cw721/v1/tx.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('../../../google/api/annotations_pb.js')

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js')

var ibc_core_client_v1_client_pb = require('../../../ibc/core/client/v1/client_pb.js')
const proto = {};
proto.uptick = {};
proto.uptick.cw721 = {};
proto.uptick.cw721.v1 = require('./tx_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.uptick.cw721.v1.MsgClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.uptick.cw721.v1.MsgPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.uptick.cw721.v1.MsgConvertNFT,
 *   !proto.uptick.cw721.v1.MsgConvertNFTResponse>}
 */
const methodDescriptor_Msg_ConvertNFT = new grpc.web.MethodDescriptor(
  '/uptick.cw721.v1.Msg/ConvertNFT',
  grpc.web.MethodType.UNARY,
  proto.uptick.cw721.v1.MsgConvertNFT,
  proto.uptick.cw721.v1.MsgConvertNFTResponse,
  /**
   * @param {!proto.uptick.cw721.v1.MsgConvertNFT} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.uptick.cw721.v1.MsgConvertNFTResponse.deserializeBinary
);


/**
 * @param {!proto.uptick.cw721.v1.MsgConvertNFT} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.uptick.cw721.v1.MsgConvertNFTResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.uptick.cw721.v1.MsgConvertNFTResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.uptick.cw721.v1.MsgClient.prototype.convertNFT =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/uptick.cw721.v1.Msg/ConvertNFT',
      request,
      metadata || {},
      methodDescriptor_Msg_ConvertNFT,
      callback);
};


/**
 * @param {!proto.uptick.cw721.v1.MsgConvertNFT} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.uptick.cw721.v1.MsgConvertNFTResponse>}
 *     Promise that resolves to the response
 */
proto.uptick.cw721.v1.MsgPromiseClient.prototype.convertNFT =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/uptick.cw721.v1.Msg/ConvertNFT',
      request,
      metadata || {},
      methodDescriptor_Msg_ConvertNFT);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.uptick.cw721.v1.MsgConvertCW721,
 *   !proto.uptick.cw721.v1.MsgConvertCW721Response>}
 */
const methodDescriptor_Msg_ConvertCW721 = new grpc.web.MethodDescriptor(
  '/uptick.cw721.v1.Msg/ConvertCW721',
  grpc.web.MethodType.UNARY,
  proto.uptick.cw721.v1.MsgConvertCW721,
  proto.uptick.cw721.v1.MsgConvertCW721Response,
  /**
   * @param {!proto.uptick.cw721.v1.MsgConvertCW721} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.uptick.cw721.v1.MsgConvertCW721Response.deserializeBinary
);


/**
 * @param {!proto.uptick.cw721.v1.MsgConvertCW721} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.uptick.cw721.v1.MsgConvertCW721Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.uptick.cw721.v1.MsgConvertCW721Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.uptick.cw721.v1.MsgClient.prototype.convertCW721 =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/uptick.cw721.v1.Msg/ConvertCW721',
      request,
      metadata || {},
      methodDescriptor_Msg_ConvertCW721,
      callback);
};


/**
 * @param {!proto.uptick.cw721.v1.MsgConvertCW721} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.uptick.cw721.v1.MsgConvertCW721Response>}
 *     Promise that resolves to the response
 */
proto.uptick.cw721.v1.MsgPromiseClient.prototype.convertCW721 =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/uptick.cw721.v1.Msg/ConvertCW721',
      request,
      metadata || {},
      methodDescriptor_Msg_ConvertCW721);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.uptick.cw721.v1.MsgTransferCW721,
 *   !proto.uptick.cw721.v1.MsgTransferCW721Response>}
 */
const methodDescriptor_Msg_TransferCW721 = new grpc.web.MethodDescriptor(
  '/uptick.cw721.v1.Msg/TransferCW721',
  grpc.web.MethodType.UNARY,
  proto.uptick.cw721.v1.MsgTransferCW721,
  proto.uptick.cw721.v1.MsgTransferCW721Response,
  /**
   * @param {!proto.uptick.cw721.v1.MsgTransferCW721} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.uptick.cw721.v1.MsgTransferCW721Response.deserializeBinary
);


/**
 * @param {!proto.uptick.cw721.v1.MsgTransferCW721} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.uptick.cw721.v1.MsgTransferCW721Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.uptick.cw721.v1.MsgTransferCW721Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.uptick.cw721.v1.MsgClient.prototype.transferCW721 =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/uptick.cw721.v1.Msg/TransferCW721',
      request,
      metadata || {},
      methodDescriptor_Msg_TransferCW721,
      callback);
};


/**
 * @param {!proto.uptick.cw721.v1.MsgTransferCW721} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.uptick.cw721.v1.MsgTransferCW721Response>}
 *     Promise that resolves to the response
 */
proto.uptick.cw721.v1.MsgPromiseClient.prototype.transferCW721 =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/uptick.cw721.v1.Msg/TransferCW721',
      request,
      metadata || {},
      methodDescriptor_Msg_TransferCW721);
};


module.exports = proto.uptick.cw721.v1;

